export const returnEnglishCopy = {
  title: "Returns",
  subtitle: "Refund only against verified line and original tender capacity.",
  "mode.receipt": "Receipt return",
  "mode.noReceipt": "No receipt",
  "action.back": "Back",
  "action.search": "Find order",
  "action.addProduct": "Add product",
  "action.addOpenItem": "Add OPENITEM",
  "action.decrease": "Decrease quantity",
  "action.increase": "Increase quantity",
  "action.confirm": "Confirm refund",
  "action.recover": "Recover refund",
  "action.reset": "Start another return",
  "search.orderLabel": "Receipt or order number",
  "search.orderPlaceholder": "Scan or enter an order number",
  "search.productLabel": "No-receipt product",
  "search.productPlaceholder": "Scan or enter a product barcode",
  "openItem.nameLabel": "OPENITEM description",
  "openItem.namePlaceholder": "Describe the returned item",
  "openItem.amountLabel": "Unit refund amount",
  "openItem.amountPlaceholder": "0.00",
  "order.summary": "Order {{order}}",
  "order.remote": "Verified online",
  "order.local": "Verified local copy",
  "order.stale": "Return records may be stale. Only proven local cash capacity is available offline.",
  "lines.title": "Items to return",
  "lines.empty": "Find an order or add a supervised no-receipt item.",
  "line.itemNumber": "Item {{itemNumber}}",
  "line.quantity": "{{selected}} of {{available}}",
  "line.quantityNoReceipt": "Quantity {{selected}}",
  "line.refund": "Refund {{amount}}",
  "capacity.title": "Original tender capacity",
  "capacity.noReceipt": "No original tender capacity. This supervised return must stay online.",
  "capacity.remaining": "{{method}} · {{amount}} available",
  "capacity.substituteOnly": "{{method}} · {{amount}} available · cash or voucher only",
  "method.cash": "Cash",
  "method.card": "Card",
  "method.voucher": "Voucher",
  "method.installment": "Installment",
  "summary.title": "Refund plan",
  "summary.selected": "Selected refund",
  "summary.method": "Preferred tender",
  "summary.rule": "The final plan may split across original tenders. Card, voucher and installment refunds require online recovery.",
  "summary.ruleReceiptDefault": "Refunds default to the original tender. Cash or voucher may be selected instead.",
  "voucherFunded.notice": "Items bought with vouchers cannot be refunded as cash or card: at least {{amount}} must be refunded as a voucher.",
  "voucherFunded.onlineRequired": "Items bought with vouchers must be refunded as a voucher, and refund vouchers can only be issued online. Reconnect and try again.",
  "voucherFunded.capacityExceeded": "The remaining original tender capacity cannot cover the voucher portion of this refund. Ask a supervisor to review the refund history.",
  "status.waitingTitle": "Refund in progress",
  "status.waitingHint": "Keep this screen open. Do not retry or change tender.",
  "status.unknownTitle": "Refund outcome unknown",
  "status.unknownHint": "Do not refund again. Reconnect and recover the existing payment attempt.",
  "status.successTitle": "Refund completed",
  "status.successOrder": "Return order {{order}}",
  "status.successAmount": "{{amount}} refunded",
  "status.failedTitle": "Refund not completed",
  "status.failedHint": "No automatic retry was made. Follow the stable error below.",
  "resolution.title": "Supervisor resolution",
  "resolution.hint": "Only if a supervisor has checked the terminal receipt and the Linkly or bank records and confirmed the customer was NOT refunded. If the refund may have gone through, choose Keep waiting and do not refund again.",
  "resolution.evidenceLabel": "Evidence (terminal receipt or record number)",
  "resolution.evidencePlaceholder": "e.g. terminal receipt number",
  "resolution.noteLabel": "Supervisor note",
  "resolution.notePlaceholder": "What was checked",
  "resolution.notRefunded": "Confirm NOT refunded",
  "resolution.keepWaiting": "Keep waiting",
  "resolution.waitingRecorded": "Supervisor decision recorded. The refund stays locked until the result is confirmed.",
  "error.RETURN_QUERY_REQUIRED": "Enter an order or product number.",
  "error.RETURN_ORDER_NOT_FOUND": "The order was not found.",
  "error.RETURN_PRODUCT_NOT_FOUND": "The product was not found.",
  "error.RETURN_SOURCE_MISMATCH": "The return source does not match the verified order. Ask a supervisor to review the original sale and refund history.",
  "error.RETURN_LINE_NOT_FOUND": "That return line is no longer available.",
  "error.RETURN_QUANTITY_INVALID": "Return quantity must be a whole number.",
  "error.RETURN_QUANTITY_EXCEEDED": "Return quantity exceeds the verified remaining quantity.",
  "error.RETURN_AMOUNT_EXCEEDED": "Refund amount exceeds the verified remaining amount.",
  "error.RETURN_NO_LINES_SELECTED": "Select at least one item to return.",
  "error.RETURN_CAPACITY_EXCEEDED": "Refund exceeds the remaining original tender capacity.",
  "error.RETURN_ONLINE_REQUIRED": "This refund requires an online connection.",
  "error.RETURN_SUPERVISOR_REQUIRED": "Supervisor authorization is required.",
  "error.RETURN_OPEN_ITEM_INVALID": "Enter a valid OPENITEM description and amount.",
  "error.RETURN_UNKNOWN_RECOVERY_REQUIRED": "Recover the existing unknown refund before any other action.",
  "error.RETURN_OPERATION_IN_PROGRESS": "A refund action is already in progress.",
  "error.RETURN_SESSION_EXPIRED": "The cashier session changed. Sign in again before continuing.",
  "error.RETURN_LOOKUP_FAILED": "The return lookup could not be completed.",
  "error.RETURN_EXECUTION_DECLINED": "The refund was declined.",
  "error.RETURN_EXECUTION_FAILED": "The refund could not be completed and was not automatically retried.",
  "error.RETURN_RECOVERY_FAILED": "Recovery did not complete. Keep this refund in recovery.",
  "error.RETURN_ORIGINAL_REFUND_UNAVAILABLE": "This card payment was confirmed on a standalone terminal and cannot be refunded to the card. Choose cash or voucher.",
  "error.RETURN_VOUCHER_SUBSTITUTE_UNAVAILABLE": "Instalment payments cannot be replaced by a voucher refund. Choose cash for this order.",
  "error.RETURN_SUPERVISOR_RESOLUTION_UNSUPPORTED": "A supervisor cannot resolve this refund on this device (partial, multi-tender or non-card refund). Keep recovering or contact support.",
  "error.RETURN_RESOLUTION_EVIDENCE_REQUIRED": "Enter the evidence reference and a note before resolving.",
  "error.RETURN_SUPERVISOR_NOT_REFUNDED": "A supervisor confirmed the customer was not refunded. This return was cancelled; start the return again if needed.",
} as const;

export type ReturnCopyKey = keyof typeof returnEnglishCopy;

const returnChineseCopy = {
  title: "退货",
  subtitle: "仅按已核验的原明细与原支付容量退款。",
  "mode.receipt": "小票退货",
  "mode.noReceipt": "无小票退货",
  "action.back": "返回",
  "action.search": "查询原单",
  "action.addProduct": "添加商品",
  "action.addOpenItem": "添加 OPENITEM",
  "action.decrease": "减少数量",
  "action.increase": "增加数量",
  "action.confirm": "确认退款",
  "action.recover": "恢复退款",
  "action.reset": "开始下一笔退货",
  "search.orderLabel": "小票号或订单号",
  "search.orderPlaceholder": "扫描或输入订单号",
  "search.productLabel": "无小票商品",
  "search.productPlaceholder": "扫描或输入商品条码",
  "openItem.nameLabel": "OPENITEM 说明",
  "openItem.namePlaceholder": "说明退回商品",
  "openItem.amountLabel": "单件退款金额",
  "openItem.amountPlaceholder": "0.00",
  "order.summary": "原单 {{order}}",
  "order.remote": "已在线核验",
  "order.local": "已核验本地副本",
  "order.stale": "退货记录可能不是最新；离线时仅可使用可证明的本地现金容量。",
  "lines.title": "选择退货商品",
  "lines.empty": "请查询原单，或添加经主管授权的无小票商品。",
  "line.itemNumber": "货号 {{itemNumber}}",
  "line.quantity": "已选 {{selected}} / 可退 {{available}}",
  "line.quantityNoReceipt": "数量 {{selected}}",
  "line.refund": "退款 {{amount}}",
  "capacity.title": "原支付退款容量",
  "capacity.noReceipt": "无原支付容量；此主管授权退货必须保持在线。",
  "capacity.remaining": "{{method}} · 可退 {{amount}}",
  "capacity.substituteOnly": "{{method}} · 可退 {{amount}} · 仅可现金或礼券退款",
  "method.cash": "现金",
  "method.card": "银行卡",
  "method.voucher": "礼券",
  "method.installment": "分期",
  "summary.title": "退款计划",
  "summary.selected": "已选退款",
  "summary.method": "优先退款方式",
  "summary.rule": "最终计划可按原支付容量拆分；银行卡、礼券和分期退款必须在线恢复。",
  "summary.ruleReceiptDefault": "默认按原支付方式退回；也可选择现金或代金券代替。",
  "voucherFunded.notice": "代金券买的商品不能退现金或退卡：至少 {{amount}} 须退代金券。",
  "voucherFunded.onlineRequired": "代金券买的商品须退代金券，退款券只能联网签发，请联网后再退。",
  "voucherFunded.capacityExceeded": "原单剩余可退额度不足以签发须退的代金券，请联系主管核对原单退款记录。",
  "status.waitingTitle": "正在退款",
  "status.waitingHint": "请保持此页面，不要重试或更换退款方式。",
  "status.unknownTitle": "退款结果未知",
  "status.unknownHint": "禁止再次退款；联网后恢复已有支付尝试。",
  "status.successTitle": "退款完成",
  "status.successOrder": "退货单 {{order}}",
  "status.successAmount": "已退款 {{amount}}",
  "status.failedTitle": "退款未完成",
  "status.failedHint": "系统未自动重试，请按下方稳定错误处理。",
  "resolution.title": "主管结案",
  "resolution.hint": "仅当主管已核对终端小票及 Linkly/银行记录，确认顾客没有收到退款时才可选择“确认未退款”。若退款可能已成功，请选择“继续等待”，切勿再次退款。",
  "resolution.evidenceLabel": "核对凭据（终端小票或记录编号）",
  "resolution.evidencePlaceholder": "例如终端小票号",
  "resolution.noteLabel": "主管备注",
  "resolution.notePlaceholder": "说明核对了什么",
  "resolution.notRefunded": "确认未退款",
  "resolution.keepWaiting": "继续等待",
  "resolution.waitingRecorded": "已记录主管决定，退款在结果确认前保持锁定。",
  "error.RETURN_QUERY_REQUIRED": "请输入订单号或商品号。",
  "error.RETURN_ORDER_NOT_FOUND": "未找到原订单。",
  "error.RETURN_PRODUCT_NOT_FOUND": "未找到商品。",
  "error.RETURN_SOURCE_MISMATCH": "退货来源与已核验原单不一致。请联系主管核对原单与退款记录后处理。",
  "error.RETURN_LINE_NOT_FOUND": "该退货明细已不可用。",
  "error.RETURN_QUANTITY_INVALID": "退货数量必须为整数。",
  "error.RETURN_QUANTITY_EXCEEDED": "退货数量超过已核验可退数量。",
  "error.RETURN_AMOUNT_EXCEEDED": "退款金额超过已核验剩余金额。",
  "error.RETURN_NO_LINES_SELECTED": "请至少选择一件退货商品。",
  "error.RETURN_CAPACITY_EXCEEDED": "退款超过原支付剩余容量。",
  "error.RETURN_ONLINE_REQUIRED": "此退款必须联网处理。",
  "error.RETURN_SUPERVISOR_REQUIRED": "需要主管授权。",
  "error.RETURN_OPEN_ITEM_INVALID": "请输入有效的 OPENITEM 说明和金额。",
  "error.RETURN_UNKNOWN_RECOVERY_REQUIRED": "完成当前未知退款恢复前禁止其他操作。",
  "error.RETURN_OPERATION_IN_PROGRESS": "已有退款操作正在进行。",
  "error.RETURN_SESSION_EXPIRED": "收银员会话已变化，请重新登录后继续。",
  "error.RETURN_LOOKUP_FAILED": "无法完成退货查询。",
  "error.RETURN_EXECUTION_DECLINED": "退款已被拒绝。",
  "error.RETURN_EXECUTION_FAILED": "退款未完成，系统没有自动重试。",
  "error.RETURN_RECOVERY_FAILED": "恢复尚未完成，请保持此退款为恢复状态。",
  "error.RETURN_ORIGINAL_REFUND_UNAVAILABLE": "该笔刷卡为独立刷卡机人工确认，无法原卡退回，请选择现金或礼券退款。",
  "error.RETURN_VOUCHER_SUBSTITUTE_UNAVAILABLE": "分期付款部分不能以礼券代替退款，该订单请选择现金。",
  "error.RETURN_SUPERVISOR_RESOLUTION_UNSUPPORTED": "此退款无法在本设备由主管结案（部分完成、多笔或非刷卡退款），请继续恢复或联系技术支持。",
  "error.RETURN_RESOLUTION_EVIDENCE_REQUIRED": "请先填写核对凭据和备注。",
  "error.RETURN_SUPERVISOR_NOT_REFUNDED": "主管已确认顾客未收到退款，本次退货已作废；如需退货请重新办理。",
} as const satisfies Record<ReturnCopyKey, string>;

const returnCopy = {
  en: returnEnglishCopy,
  zh: returnChineseCopy,
} as const;

export type ReturnLocale = keyof typeof returnCopy;

export function resolveReturnLocale(language?: string): ReturnLocale {
  return language?.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function returnText(
  locale: ReturnLocale,
  key: ReturnCopyKey,
  values?: Readonly<Record<string, string | number>>,
): string {
  const template = returnCopy[locale][key];
  if (!values) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (placeholder, name: string) => {
    const value = values[name];
    return value === undefined ? placeholder : String(value);
  });
}
